### ISSUE TITLE
style.css周り

### ISSUE THREAD

**Issue by loop0429** [shamo-9118/todo#3]
https://github.com/shamo-9118/todo/blob/5feb412b319053446a03500e393eef5c32715450/style.css#L1-L6
marginが二つあります

https://github.com/shamo-9118/todo/blob/5feb412b319053446a03500e393eef5c32715450/style.css#L6-L7
改行のルールを統一して

プロパティの並び順を意識してください。下記、視覚整形モデルを参考に。
https://zenn.dev/web_tips/articles/f1167f4314dcb3#%E8%A6%96%E8%A6%9A%E6%95%B4%E5%BD%A2%E3%83%A2%E3%83%87%E3%83%AB

**Comment by loop0429** [comment]
@shamo-9118 
まだ直ってないす
https://github.com/shamo-9118/todo/blob/fd7577764ab2a5475f4688efe50b8453459b0482/style.css#L68-L73

**Comment by shamo-9118** [comment]
大変失礼いたしました🙇‍♂️🙇‍♂️
今日も見てくださりありがとうございます！！！！！
お手隙の際にまた見てくださると大変嬉しく感激します！！

**Comment by loop0429** [comment]
![LGTM](https://image.lgtmoon.dev/138720)
